"""Subprocess lifecycle for Hermes Agent.

The dashboard never imports hermes-agent. Instead, it spawns
``hermes gateway run --accept-hooks`` as a subprocess, captures its
combined stdout+stderr, tails the log files under ``~/.hermes/logs``,
and serves those lines to the browser over the existing ``/ws/logs``
websocket (re-using the same fanout the pipeline subprocess uses).

Why this module exists separately from :mod:`web_ui.process_manager`
====================================================================

``process_manager.py`` is tightly coupled to the speech-to-speech
pipeline: it builds argv from CLI flags, mirrors user env vars, and
injects ``OPENAI_API_KEY`` on the user's behalf. None of that applies
to hermes-agent. Hermes is configured purely through environment
variables (``API_SERVER_ENABLED``, ``API_SERVER_KEY``, etc.), and the
launch command is fixed (``hermes gateway run --accept-hooks``). So we
keep the two lifecycles separate to avoid leaking pipeline assumptions
into the hermes side.

What this module owns
=====================

- Spawning ``hermes gateway run --accept-hooks`` with the env vars
  ``API_SERVER_ENABLED=true``, ``API_SERVER_KEY=<auto-generated>``,
  ``API_SERVER_PORT=8642`` (default, configurable),
  ``API_SERVER_HOST=127.0.0.1`` (loopback only — see security note).
  ``API_SERVER_MODEL_NAME`` is intentionally NOT injected — see
  :meth:`_build_env`.
- Reading its stdout+stderr line by line in a background thread.
- A ring buffer of the last ``BUFFER_SIZE`` lines for the UI to fetch
  on reconnect.
- Stop / cancel / kill cleanly across Windows and POSIX.
- Health probe (``GET /health``) used by :meth:`HermesProcess.get_status`
  to populate the "running? port? ready?" panel.

Security note
=============

We bind to ``127.0.0.1`` by default and generate a strong random
``API_SERVER_KEY`` on first start. Even on loopback, hermes-agent
enforces the key (verified by the upstream ``security_audit_startup.py``
in hermes-agent 0.19+), so a key is required — we never bind without
one. The key is auto-generated and persisted in
``web_ui_settings.json`` so the dashboard and the hermes subprocess
agree on it across restarts.
"""

from __future__ import annotations

import logging
import os
import queue
import re
import secrets
import subprocess
import threading
import time
from collections import deque
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable, Optional

logger = logging.getLogger(__name__)


BUFFER_SIZE = 5000
STOP_TIMEOUT_S = 5.0

# Default port matches hermes-agent's own convention (see
# hermes_cli/service_manager.py: ``API_SERVER_PORT`` defaults to 8642
# for the default profile's gateway). The user can override via the
# Hermes tab.
DEFAULT_PORT = 8642
DEFAULT_HOST = "127.0.0.1"

# Hermes writes detailed per-turn output to files under ~/.hermes/logs.
# We tail these files while the gateway is running so the dashboard's
# Hermes log panel shows thinking / skills / tool calls, not just the
# minimal stderr banner. Health-probe lines are filtered because the
# dashboard hits /health every 2 s and would otherwise drown the panel.
TAIL_LOG_FILES = ["agent.log", "gateway.log", "errors.log"]
LOG_POLL_INTERVAL_S = 0.5


# Matches hermes-agent's own logging format:
#   "2026-07-23 14:33:12,345 - hermes_cli.gateway - WARNING - hello"
# Timestamp and name are optional so that model load banners, library
# imports, and tracebacks still get a sensible level.
_LOG_LINE_RE = re.compile(
    r"^(?P<ts>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}(?:,\d+)?)?\s*"
    r"(?:-?\s*(?P<name>[\w.]+)\s*-\s*)?"
    r"(?P<level>DEBUG|INFO|WARNING|ERROR|CRITICAL)\s*-\s*"
    r"(?P<msg>.*)$"
)


@dataclass
class LogLine:
    """A single captured line from the hermes subprocess."""

    index: int
    timestamp: float
    level: str
    text: str

    def to_dict(self) -> dict[str, Any]:
        return {
            "index": self.index,
            "timestamp": self.timestamp,
            "level": self.level,
            "text": self.text,
        }


@dataclass
class _State:
    """Mutable state guarded by ``_lock``."""

    process: Optional[subprocess.Popen] = None
    started_at: Optional[float] = None
    # Monotonic counter assigned to each LogLine. Used by the client to
    # request ``/api/hermes/logs?since=<n>`` on reconnect.
    log_index: int = 0
    # Buffer is created in __post_init__ because deque(maxlen=...) has
    # mutable semantics that the dataclass machinery doesn't like as a
    # default.
    buffer: deque = field(default_factory=lambda: deque(maxlen=BUFFER_SIZE))
    subscribers: list[Callable[[LogLine], None]] = field(default_factory=list)
    reader_thread: Optional[threading.Thread] = None
    subscriber_queue: "queue.Queue[LogLine]" = field(default_factory=queue.Queue)
    # Health-probe state. We probe /health on a background thread so
    # ``get_status()`` is always fast (no blocking on the hermes
    # subprocess).
    health: dict[str, Any] = field(default_factory=lambda: {"ready": False, "checked_at": 0.0, "error": None})


class HermesProcess:
    """Owns one hermes-agent subprocess at a time.

    Instantiate once per dashboard. Thread-safe.

    Configuration is read from a settings dict with the following keys
    (all optional — defaults shown)::

        {
            "hermes": {
                "port": 8642,
                "host": "127.0.0.1",
                "api_key": "<auto-generated if missing>",
                "model_name": "qwen3.5:9b",
                "log_level": "verbose",
            }
        }
    """

    def __init__(self, repo_root: Path) -> None:
        self._repo_root = Path(repo_root)
        self._lock = threading.Lock()
        self._state = _State()
        self._fanout_thread: Optional[threading.Thread] = None
        self._fanout_stop = threading.Event()
        self._health_thread: Optional[threading.Thread] = None
        self._health_stop = threading.Event()
        # One (thread, stop_event) pair per tailed log file.
        self._tail_threads: list[tuple[threading.Thread, threading.Event]] = []
        # Cache for get_active_model() — `hermes config get` is a
        # subprocess spawn, so we don't want to pay it on every 2 s
        # status poll. The TTL keeps the displayed model fresh enough
        # that a `hermes model` swap in the terminal shows up within a
        # few seconds without spawning a process on every tick.
        self._active_model_cache: dict[str, Any] = {}
        self._active_model_cache_ts: float = 0.0

    # ------------------------------------------------------------------
    # Settings helpers
    # ------------------------------------------------------------------

    @staticmethod
    def ensure_api_key(settings: dict[str, Any]) -> str:
        """Return the persisted ``api_key``, generating one if missing.

        Mutates ``settings["hermes"]["api_key"]`` in place so the
        caller can persist it. Idempotent — re-running on an already-
        populated key is a no-op.
        """
        hermes_cfg = settings.setdefault("hermes", {})
        key = hermes_cfg.get("api_key")
        if not isinstance(key, str) or not key.strip():
            key = secrets.token_hex(32)
            hermes_cfg["api_key"] = key
        return key

    @staticmethod
    def resolve_config(settings: dict[str, Any]) -> dict[str, Any]:
        """Return a normalized hermes config block with all defaults applied."""
        hermes_cfg = settings.get("hermes") or {}
        if not isinstance(hermes_cfg, dict):
            hermes_cfg = {}
        port = hermes_cfg.get("port") or DEFAULT_PORT
        try:
            port = int(port)
        except (TypeError, ValueError):
            port = DEFAULT_PORT
        host = hermes_cfg.get("host") or DEFAULT_HOST
        if not isinstance(host, str) or not host:
            host = DEFAULT_HOST
        model_name = hermes_cfg.get("model_name") or "qwen3.5:9b"
        if not isinstance(model_name, str):
            model_name = "qwen3.5:9b"
        log_level = hermes_cfg.get("log_level") or "verbose"
        if log_level not in {"default", "verbose", "debug"}:
            log_level = "verbose"
        return {
            "port": port,
            "host": host,
            "api_key": str(hermes_cfg.get("api_key") or ""),
            "model_name": model_name,
            "log_level": log_level,
        }

    # ------------------------------------------------------------------
    # Lifecycle
    # ------------------------------------------------------------------

    def start(self, settings: dict[str, Any]) -> None:
        """Start (or restart) the hermes-agent subprocess."""
        with self._lock:
            if self._state.process is not None and self._state.process.poll() is None:
                raise RuntimeError("Hermes is already running; stop it first.")
            cfg = self.resolve_config(settings)
            api_key = self.ensure_api_key(settings)
            cfg["api_key"] = api_key
            self._state.started_at = time.time()
            self._state.log_index = 0
            self._state.buffer.clear()
            self._state.health = {"ready": False, "checked_at": 0.0, "error": None}
            env = self._build_env(cfg)
            logger.info(
                "Starting hermes gateway on %s:%s (model=%s, log_level=%s)",
                cfg["host"],
                cfg["port"],
                cfg["model_name"],
                cfg.get("log_level", "verbose"),
            )
            self._stop_tailing()
            self._state.process = self._spawn(env, cfg)
            self._state.reader_thread = threading.Thread(
                target=self._reader_loop, args=(self._state.process,), daemon=True
            )
            self._state.reader_thread.start()
            self._start_tailing(cfg)

        if self._fanout_thread is None or not self._fanout_thread.is_alive():
            self._fanout_stop.clear()
            self._fanout_thread = threading.Thread(target=self._fanout_loop, daemon=True)
            self._fanout_thread.start()

        # Start the health-probe loop. We probe every 2s in the
        # background so get_status() never blocks. The probe also
        # tells us when the server is actually ready (the subprocess
        # is up but the aiohttp listener may not be bound yet).
        self._health_stop.clear()
        if self._health_thread is None or not self._health_thread.is_alive():
            self._health_thread = threading.Thread(target=self._health_loop, args=(cfg,), daemon=True)
            self._health_thread.start()

    def stop(self) -> None:
        """Politely stop hermes (SIGTERM, escalating to SIGKILL after timeout).

        No-op if not running.
        """
        with self._lock:
            proc = self._state.process
            if proc is None or proc.poll() is not None:
                self._state.process = None
                return
            logger.info("Stopping hermes (pid=%s)", proc.pid)
            self._terminate(proc)
        # Wait outside the lock so the reader thread can finish flushing.
        try:
            proc.wait(timeout=STOP_TIMEOUT_S)
        except subprocess.TimeoutExpired:
            logger.warning("Hermes did not exit within %ss; killing", STOP_TIMEOUT_S)
            with self._lock:
                p = self._state.process
            if p is not None and p.poll() is None:
                p.kill()
                p.wait()
        self._stop_tailing()
        with self._lock:
            self._state.process = None
            self._state.started_at = None
            self._state.health = {"ready": False, "checked_at": 0.0, "error": None}

    def kill(self) -> None:
        """Hard kill the hermes subprocess (SIGKILL, immediate)."""
        with self._lock:
            proc = self._state.process
            if proc is None or proc.poll() is not None:
                self._state.process = None
                return
            logger.warning("Killing hermes (pid=%s)", proc.pid)
            try:
                proc.kill()
            except (OSError, ProcessLookupError):
                pass
        try:
            proc.wait(timeout=STOP_TIMEOUT_S)
        except subprocess.TimeoutExpired:
            logger.error("Hermes did not die after SIGKILL")
        self._stop_tailing()
        with self._lock:
            self._state.process = None
            self._state.started_at = None
            self._state.health = {"ready": False, "checked_at": 0.0, "error": None}

    def cancel(self) -> None:
        """Send a cancel signal to the running hermes session.

        Implemented as a best-effort: we POST to ``/v1/runs/stop`` on
        the local hermes server (it returns 404 if no run is active,
        which is fine). When no run is in progress, this is a no-op.
        We use the same api_key the subprocess was started with.

        This is what the amber "Cancel hermes" button maps to.
        """
        with self._lock:
            proc = self._state.process
            cfg = self._state.health.get("config")
        if proc is None or proc.poll() is not None or not isinstance(cfg, dict):
            return
        import httpx

        url = f"http://{cfg['host']}:{cfg['port']}/v1/runs/stop"
        try:
            with httpx.Client(timeout=2.0) as client:
                # 404 means "no active run" — that's a successful no-op
                # from our perspective.
                client.post(
                    url,
                    headers={
                        "Authorization": f"Bearer {cfg.get('api_key', '')}",
                        "Content-Type": "application/json",
                    },
                    content=b"{}",
                )
        except Exception as e:  # noqa: BLE001
            logger.debug("cancel() failed (probably no active run): %s", e)

    def is_running(self) -> bool:
        with self._lock:
            return self._state.process is not None and self._state.process.poll() is None

    def get_status(self, settings: Optional[dict[str, Any]] = None) -> dict[str, Any]:
        """Snapshot of the current state for the dashboard's status panel."""
        with self._lock:
            proc = self._state.process
            running = proc is not None and proc.poll() is None
            cfg = self.resolve_config(settings) if isinstance(settings, dict) else None
            health = dict(self._state.health)
            return {
                "running": running,
                "pid": proc.pid if proc is not None else None,
                "exit_code": proc.returncode if proc is not None else None,
                "started_at": self._state.started_at,
                "uptime_s": ((time.time() - self._state.started_at) if (running and self._state.started_at) else 0.0),
                "port": cfg["port"] if cfg else DEFAULT_PORT,
                "host": cfg["host"] if cfg else DEFAULT_HOST,
                "model_name": cfg["model_name"] if cfg else "",
                "ready": health.get("ready", False),
                "last_health_error": health.get("error"),
                "last_health_check": health.get("checked_at"),
            }

    # ------------------------------------------------------------------
    # Active model (resolved from `hermes config`, not /v1/models)
    # ------------------------------------------------------------------

    # `hermes config get` is a subprocess spawn; cache briefly so the
    # 2 s status poll doesn't spawn one every tick.
    _ACTIVE_MODEL_TTL_S = 5.0

    def get_active_model(self) -> dict[str, Any]:
        """Resolve the model hermes is actually configured to use.

        ``/v1/models`` only advertises a label (the
        ``API_SERVER_MODEL_NAME`` env var or the ``hermes-agent``
        virtual model) — it does NOT report the inference model. The
        real model is whatever ``hermes config get model`` resolves to
        (the user's ``hermes model`` / ``hermes config`` selection),
        which is what hermes routes requests to. We read it here and
        cache it briefly so the 2 s status poll doesn't spawn a
        subprocess on every tick.

        Returns ``{"model", "provider", "base_url", "error"}`` where
        ``error`` is None on success. ``model`` is None when hermes
        isn't configured or the CLI is missing.
        """
        with self._lock:
            cached = self._active_model_cache
            if cached and (time.time() - self._active_model_cache_ts) < self._ACTIVE_MODEL_TTL_S:
                return dict(cached)

        try:
            binary = _find_hermes_binary()
        except FileNotFoundError as e:
            result = {"model": None, "provider": None, "base_url": None, "error": str(e)}
            self._cache_active_model(result)
            return result

        parsed = self._read_hermes_model(binary)
        if not parsed.get("model"):
            parsed["error"] = (
                parsed.get("error")
                or "no model configured in hermes (run `hermes model`)"
            )
        self._cache_active_model(parsed)
        return parsed

    def _read_hermes_model(self, binary: str) -> dict[str, Any]:
        """Run ``hermes config get model`` (falling back to ``model.default``)."""
        try:
            proc = subprocess.run(
                [binary, "config", "get", "model"],
                capture_output=True,
                text=True,
                timeout=4.0,
            )
        except Exception as e:  # noqa: BLE001
            return {"model": None, "provider": None, "base_url": None,
                    "error": f"{type(e).__name__}: {e}"}

        parsed = self._parse_hermes_config_model(proc.stdout)
        if not parsed.get("model"):
            # model may be set as a bare string rather than a dict;
            # `config get model.default` returns just the value.
            try:
                proc2 = subprocess.run(
                    [binary, "config", "get", "model.default"],
                    capture_output=True,
                    text=True,
                    timeout=4.0,
                )
            except Exception:  # noqa: BLE001
                proc2 = None
            if proc2 is not None:
                val = proc2.stdout.strip()
                if val and "not set" not in val.lower():
                    parsed["model"] = val
        if not parsed.get("model") and proc.stderr.strip():
            parsed["error"] = proc.stderr.strip()[:200]
        return parsed

    def _cache_active_model(self, result: dict[str, Any]) -> None:
        with self._lock:
            self._active_model_cache = dict(result)
            self._active_model_cache_ts = time.time()

    @staticmethod
    def _parse_hermes_config_model(stdout: str) -> dict[str, Any]:
        """Parse the ``key: value`` lines from ``hermes config get model``.

        Output looks like::

            base_url: https://ollama.com/v1
            default: minimax-m3
            provider: ollama-cloud

        Unknown shapes fall through gracefully (fields stay None).
        """
        out: dict[str, Any] = {"model": None, "provider": None, "base_url": None, "error": None}
        for line in (stdout or "").splitlines():
            line = line.strip()
            if not line or ":" not in line:
                continue
            key, _, val = line.partition(":")
            key = key.strip()
            val = val.strip()
            if key == "default":
                out["model"] = val or None
            elif key == "provider":
                out["provider"] = val or None
            elif key == "base_url":
                out["base_url"] = val or None
        return out

    # ------------------------------------------------------------------
    # Logs
    # ------------------------------------------------------------------

    def get_log_buffer(self, since: int = 0) -> list[dict[str, Any]]:
        with self._lock:
            return [line.to_dict() for line in self._state.buffer if line.index >= since]

    def subscribe(self, callback: Callable[[LogLine], None]) -> None:
        with self._lock:
            self._state.subscribers.append(callback)

    def unsubscribe(self, callback: Callable[[LogLine], None]) -> None:
        with self._lock:
            try:
                self._state.subscribers.remove(callback)
            except ValueError:
                pass

    # ------------------------------------------------------------------
    # Internals
    # ------------------------------------------------------------------

    def _spawn(self, env: dict[str, str], cfg: dict[str, Any]) -> subprocess.Popen:
        """Launch ``hermes gateway run --accept-hooks`` in a cross-platform way.

        List argv (no shell) and explicit cwd ensure the same behavior on
        Linux, macOS, and Windows. ``--accept-hooks`` makes hermes
        auto-approve unseen shell hooks so it never blocks on a prompt
        — this is critical for a non-interactive subprocess.
        """
        # Locate the hermes CLI. It is normally on PATH as ``hermes``,
        # but a user with multiple Python venvs may have it elsewhere.
        # We fall back to the same logic the user uses in their shell:
        # ``which hermes`` first, then ``~/.hermes/hermes-agent/venv/bin/hermes``,
        # then a hard error if neither is found.
        hermes_bin = _find_hermes_binary()
        argv = [hermes_bin, "gateway", "run", "--accept-hooks"]
        log_level = cfg.get("log_level", "verbose")
        if log_level == "verbose":
            argv.append("-v")
        elif log_level == "debug":
            argv.extend(["-v", "-v"])  # equivalent to -vv
        kwargs: dict[str, Any] = {
            "args": argv,
            "cwd": str(self._repo_root),
            "env": env,
            "stdout": subprocess.PIPE,
            "stderr": subprocess.STDOUT,
            "stdin": subprocess.DEVNULL,
            "bufsize": 1,  # line buffered
            "text": True,
            "encoding": "utf-8",
            "errors": "replace",
        }
        if os.name == "nt":
            # Detach so Ctrl+C / closing the dashboard terminal doesn't
            # propagate down. CREATE_NEW_PROCESS_GROUP is the right knob
            # on Windows; we then call ``proc.send_signal(CTRL_BREAK_EVENT)``
            # to ask it to shut down cleanly.
            kwargs["creationflags"] = subprocess.CREATE_NEW_PROCESS_GROUP  # type: ignore[attr-defined]
        else:
            # POSIX: put hermes in its own process group so the
            # dashboard's SIGTERM (sent during a torch-wheel restart)
            # does not propagate down to hermes. Without this, every
            # torch-install-induced dashboard restart killed hermes and
            # forced the user to re-start it (and lose the conversation).
            kwargs["start_new_session"] = True
        return subprocess.Popen(**kwargs)

    def _terminate(self, proc: subprocess.Popen) -> None:
        """Politely ask hermes to stop, escalating to kill if needed."""
        if os.name == "nt":
            try:
                proc.send_signal(subprocess.CTRL_BREAK_EVENT)  # type: ignore[attr-defined]
                return
            except (OSError, ValueError):
                pass
        try:
            proc.terminate()
        except (OSError, ProcessLookupError):
            pass

    def _reader_loop(self, proc: subprocess.Popen) -> None:
        """Read stdout until EOF and append each line to the buffer / queue."""
        assert proc.stdout is not None
        try:
            for raw in proc.stdout:
                line = raw.rstrip("\n")
                self._append(line)
        except Exception:  # noqa: BLE001
            logger.exception("Hermes reader loop crashed")
        finally:
            self._append(f"[dashboard] hermes subprocess exited with code {proc.returncode}")

    def _append(self, text: str) -> None:
        level = "OTHER"
        m = _LOG_LINE_RE.match(text)
        if m:
            level = m.group("level") or "OTHER"
        with self._lock:
            self._state.log_index += 1
            entry = LogLine(
                index=self._state.log_index,
                timestamp=time.time(),
                level=level,
                text=text,
            )
            self._state.buffer.append(entry)
            self._state.subscriber_queue.put(entry)

    def _start_tailing(self, cfg: dict[str, Any]) -> None:
        """Start a tail thread for each known Hermes log file.

        We open the file at its current end so the dashboard only shows
        logs produced after this Start. If ~/.hermes/logs does not exist
        yet (e.g. first install), the tailer threads simply wait until
        Hermes creates it.
        """
        log_dir = Path.home() / ".hermes" / "logs"
        for name in TAIL_LOG_FILES:
            path = log_dir / name
            stop = threading.Event()
            t = threading.Thread(target=self._tail_file_loop, args=(path, stop), daemon=True)
            self._tail_threads.append((t, stop))
            t.start()

    def _stop_tailing(self) -> None:
        """Signal every tail thread to stop and join them."""
        for _, stop in self._tail_threads:
            stop.set()
        for t, _ in self._tail_threads:
            try:
                t.join(timeout=1.0)
            except RuntimeError:
                pass
        self._tail_threads.clear()

    def _tail_file_loop(self, path: Path, stop: threading.Event) -> None:
        """Tail one Hermes log file and feed new lines into ``_append``."""
        while not stop.is_set():
            try:
                if not path.exists():
                    stop.wait(LOG_POLL_INTERVAL_S)
                    continue
                with open(path, "r", encoding="utf-8", errors="replace") as f:
                    f.seek(0, os.SEEK_END)
                    while not stop.is_set():
                        line = f.readline()
                        if line:
                            text = line.rstrip("\n")
                            # Filter the dashboard's own /health probes.
                            if "GET /health" in text:
                                continue
                            self._append(f"[{path.name}] {text}")
                            continue
                        # No new data: check for truncation/rotation.
                        try:
                            pos = f.tell()
                            size = path.stat().st_size
                            if size < pos:
                                f.seek(0, os.SEEK_END)
                        except OSError:
                            pass
                        stop.wait(LOG_POLL_INTERVAL_S)
            except Exception:  # noqa: BLE001
                logger.exception("Hermes log tailer crashed for %s", path)
                stop.wait(LOG_POLL_INTERVAL_S)

    def _fanout_loop(self) -> None:
        """Single consumer of the log queue; calls each subscriber without blocking."""
        while not self._fanout_stop.is_set():
            try:
                entry = self._state.subscriber_queue.get(timeout=0.2)
            except queue.Empty:
                continue
            with self._lock:
                subs = list(self._state.subscribers)
            for cb in subs:
                try:
                    cb(entry)
                except Exception:  # noqa: BLE001
                    logger.exception("Hermes log subscriber raised")

    def _health_loop(self, cfg: dict[str, Any]) -> None:
        """Periodically probe ``GET /health`` so :meth:`get_status` stays fast.

        Polls every 2s. Updates ``_state.health`` under the lock with
        ``ready`` (bool), ``checked_at`` (epoch seconds), ``error`` (str
        or None), and ``config`` (the resolved config so cancel() can
        build the right URL).
        """
        import httpx

        # Stash the cfg so cancel() doesn't need a separate settings
        # round-trip.
        with self._lock:
            self._state.health["config"] = cfg
        url = f"http://{cfg['host']}:{cfg['port']}/health"
        # Initial back-off so we don't hammer the loop while hermes is
        # still booting.
        next_check = time.time() + 1.0
        while not self._health_stop.is_set():
            now = time.time()
            wait = next_check - now
            if wait > 0:
                if self._health_stop.wait(timeout=wait):
                    return
            # If the process died, exit cleanly.
            with self._lock:
                proc = self._state.process
            if proc is None or proc.poll() is not None:
                return
            try:
                with httpx.Client(timeout=1.5) as client:
                    r = client.get(url)
                ready = 200 <= r.status_code < 300
                err = None if ready else f"HTTP {r.status_code}"
            except Exception as e:  # noqa: BLE001
                ready = False
                err = f"{type(e).__name__}: {e}"
            with self._lock:
                self._state.health = {
                    "ready": ready,
                    "checked_at": time.time(),
                    "error": err,
                    "config": cfg,
                }
            next_check = time.time() + 2.0

    def _build_env(self, cfg: dict[str, Any]) -> dict[str, str]:
        """Build the subprocess env from the current process env + hermes overrides.

        The five ``API_SERVER_*`` env vars are how hermes-agent
        configures the api_server platform. Setting them here is
        sufficient — hermes-agent does not consume CLI flags for these.
        """
        out = dict(os.environ)
        out["API_SERVER_ENABLED"] = "true"
        out["API_SERVER_KEY"] = cfg["api_key"]
        out["API_SERVER_PORT"] = str(cfg["port"])
        out["API_SERVER_HOST"] = cfg["host"]
        # NOTE: we deliberately do NOT inject ``API_SERVER_MODEL_NAME``.
        # That env var only controls the model name hermes advertises on
        # ``/v1/models`` (see api_server._resolve_model_name) — it does
        # NOT select the inference model (that comes from the user's
        # ``hermes model`` / ``hermes config`` selection, read live per
        # request). Injecting the dashboard's ``hermes.model_name``
        # setting (default ``qwen3.5:9b``) made ``/v1/models`` advertise
        # a model the user never chose, while hermes actually ran
        # whatever ``hermes config get model.default`` resolves to. With
        # the var unset, ``/v1/models`` falls back to hermes's designed
        # virtual model (``hermes-agent`` or the active profile name) —
        # truthful and never a stale override. The dashboard reads the
        # *real* loaded model via :meth:`get_active_model` for display.
        # Force unbuffered output from the child so logs stream in real time.
        out["PYTHONUNBUFFERED"] = "1"
        return out


def _find_hermes_binary() -> str:
    """Locate the ``hermes`` CLI executable on this machine.

    Tries, in order:

    1. ``shutil.which("hermes")`` — normal PATH lookup. Works when
       hermes is installed system-wide or via pipx/uv.
    2. The per-user venv at ``~/.hermes/hermes-agent/venv/bin/hermes``
       (POSIX) or ``%USERPROFILE%\\.hermes\\hermes-agent\\venv\\Scripts\\hermes.exe``
       (Windows). This is where the upstream installer drops it.
    3. Raises ``FileNotFoundError`` with a helpful message.
    """
    import shutil

    found = shutil.which("hermes")
    if found:
        return found
    # Common install location used by the upstream installer.
    if os.name == "nt":
        candidates = [
            Path.home() / ".hermes" / "hermes-agent" / "venv" / "Scripts" / "hermes.exe",
        ]
    else:
        candidates = [
            Path.home() / ".hermes" / "hermes-agent" / "venv" / "bin" / "hermes",
            Path.home() / ".local" / "bin" / "hermes",
        ]
    for c in candidates:
        if c.is_file() and os.access(c, os.X_OK):
            return str(c)
    raise FileNotFoundError(
        "Could not find the `hermes` CLI on PATH. Install hermes-agent "
        "(see https://github.com/NousResearch/hermes-agent) and ensure "
        "`hermes` is runnable, then reload the Hermes tab."
    )
